### ISSUE TITLE
Do not use webpack, store builds in the npm registry

### ISSUE THREAD

**Issue by a-x-** [a-x-/react-easy-print#6]
- reduce bundle size
- enable project-level tree shaking
- add package.json "sideEffects": false
- end-developer defined browserlist configs (`require('react-easy-print/src')`)

## todo
- [x] use babel 
- [x] use [babel-plugin-transform-import-css](https://github.com/a-x-/babel-plugin-transform-import-css) for css bundling
- [x] do not store builds in git repository
- [x] npm run build
